english version 初稿完成
mengshukeji/Luckysheet pull request #36
Opened 2020-09-15 12:02 UTC by qq6690876

english version 初稿完成

2020-09-17 13:11 UTC, Dushusir requested changes

2020-09-17 13:11 UTC, Dushusir commented on docs/guide/sheet.md
> +        "hasRowFooter": false //is included footers
footers changed to footer

2020-09-17 13:11 UTC, Dushusir commented on docs/guide/sheet.md
> +        "load": "1", //check whether this sheed loaded
How about this： `Check whether this sheet has been loaded`

2020-09-25 06:19 UTC, qq6690876 commented on docs/guide/sheet.md
> +    `r` represents the row, `c` represents the column, and `v` represents the value of the cell. value could be char, number, or object
thanks

2020-09-25 06:21 UTC, closed without merging

2020-09-25 06:21 UTC, qq6690876 commented
create a new request