bug fix
mengshukeji/Luckysheet pull request #56
Opened 2020-09-29 01:55 UTC by javahuang

1. fix(more formats toolbar): fix more formats toolbar can't sync with cell
2. fix mac delete button can't delete cell
3. fix can't delete cell with inline-style

2020-10-09 07:54 UTC, mengshukeji approved these changes
good job!

2020-10-09 08:15 UTC, wbfsa requested changes

2020-10-09 08:15 UTC, wbfsa commented on src/controllers/rowColumnOperation.js
> +                            }
```suggestion
                            if(d[r][c]["ct"] != null) {
                                delete d[r][c]["ct"]["s"]
                            }
```
这里需要把d[r][c]["ct"].t == 'inlineStr' ,inlineStr重置为g，因为单元格为行内样式的话，会设置t为inlineStr，这里不重置会有隐患

2020-10-12 01:48 UTC, mengshukeji commented
感谢贡献，期待加入我们开发组，加这个微信：liurunze---

2020-10-12 15:19 UTC, javahuang commented on src/controllers/rowColumnOperation.js
> +                            }
```js
if(d[r][c]["ct"] != null && d[r][c]["ct"].t == 'inlineStr'){
  delete d[r][c]["ct"];
 }
```
刚看这个问题已经被别的同学修复了，我给这个删了

2020-10-12 16:22 UTC, Dto161 approved these changes

2020-10-13 17:50 UTC, fylo5 approved these changes

2020-10-13 17:56 UTC, wbfsa approved these changes

2020-10-13 17:57 UTC, merged